# Generated by Django 3.2.20 on 2023-08-18 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contribution', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='premium',
            options={'managed': True},
        ),
    ]
