# Generated by Django 3.2.20 on 2023-08-18 23:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payer', '0001_initial'),
        ('policy', '0005_auto_20230622_1854'),
        ('contribution', '0002_alter_premium_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='premium',
            name='network_operator',
            field=models.CharField(blank=True, db_column='networkOperator', max_length=1, null=True),
        ),
        # migrations.AddField(
        #     model_name='premium',
        #     name='payer',
        #     field=models.ForeignKey(blank=True, db_column='PayerID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='premiums', to='payer.payer'),
        # ),
        migrations.AddField(
            model_name='premium',
            name='payment_number',
            field=models.CharField(blank=True, db_column='paymentNumber', max_length=20, null=True),
        ),
        # migrations.AddField(
        #     model_name='premium',
        #     name='policy',
        #     field=models.ForeignKey(db_column='PolicyID', default=django.utils.timezone.now, on_delete=django.db.models.deletion.DO_NOTHING, related_name='premiums', to='policy.policy'),
        #     preserve_default=False,
        # ),
        # migrations.AlterField(
        #     model_name='premium',
        #     name='is_offline',
        #     field=models.BooleanField(blank=True, db_column='isOffline', default=False, null=True),
        # ),
        # migrations.AlterField(
        #     model_name='premium',
        #     name='is_photo_fee',
        #     field=models.BooleanField(blank=True, db_column='isPhotoFee', default=False, null=True),
        # ),
        # migrations.AlterField(
        #     model_name='premium',
        #     name='pay_type',
        #     field=models.CharField(db_column='PayType', max_length=1),
        # ),
    ]
