# Generated by Django 3.2.20 on 2023-08-31 16:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contribution', '0003_auto_20230818_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='premium',
            name='cron_treated',
            field=models.BooleanField(blank=True, db_column='CronTreated', default=False, null=True),
        ),
        migrations.AddField(
            model_name='premium',
            name='paytoken',
            field=models.TextField(blank=True, db_column='PayToken', null=True),
        ),
    ]
